# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer
    Domain: example.com
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # ---------------------------------------------------------------------------
    Specs:
      - Hostname: orderer
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  - Name: Manufacturer
    Domain: Manufacturer.example.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Dealer
    Domain: Dealer.example.com
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Insurance
    Domain: Insurance.example.com
    Template:
      Count: 1
    Users:
      Count: 1



  - Name: Gdt
    Domain: Gdt.example.com
    Template:
      Count: 1
    Users:
      Count: 1